# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: v2-indexer

contracts:
  - name: Factory
    events:
      - event: PairCreated(address indexed token0, address indexed token1, address pair, uint256 )
  - name: Pair
    events:
      - event: Burn(address indexed sender, uint256 amount0, uint256 amount1, address indexed to)
        field_selection:
          transaction_fields:
            - hash
      - event: Mint(address indexed sender, uint256 amount0, uint256 amount1)
        field_selection:
          transaction_fields:
            - hash
      - event: Swap(address indexed sender, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out, address indexed to)
        field_selection:
          transaction_fields:
            - hash
      - event: Sync(uint112 reserve0, uint112 reserve1)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
        field_selection:
          transaction_fields:
            - hash

chains:
  - id: 31337 # Local Anvil network default chainId
    rpc:
      url: http://localhost:8545 # RPC URL for your local Anvil network
    start_block: 0 # Specify the starting block
    contracts:
      - name: Factory
        address:
          - 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
      - name: Pair
  - id: 10143
    start_block: 0
    contracts:
      - name: Factory
        address:
          - 0x733e88f248b742db6c14c0b1713af5ad7fdd59d0
      - name: Pair
